export const LOGIN_USER = "LOGIN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";

export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";

export const SET_MYCHATS = "SET_MYCHATS";
export const EDIT_SINGLE_MYCHAT = "EDIT_SINGLE_MYCHAT";

export const SEND_NOTIFICATION = "SEND_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
